In [1]:
import tensorflow as tf 
import numpy as np 
import pandas as pd 
import os 

In [2]:
df= pd.read_csv('/kaggle/input/jigsaw-toxic-comment-classification-challenge/train.csv')

In [3]:
df.drop(['id'],axis=1,inplace=True)

In [4]:
df[df['toxic']==1]

comment_text  toxic  \
6            COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1   
12      Hey... what is it..\n@ | talk .\nWhat is it......      1   
16      Bye! \n\nDon't look, come or think of comming ...      1   
42      You are gay or antisemmitian? \n\nArchangel WH...      1   
43               FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!      1   
...                                                   ...    ...   
159494  "\n\n our previous conversation \n\nyou fuckin...      1   
159514                  YOU ARE A MISCHIEVIOUS PUBIC HAIR      1   
159541  Your absurd edits \n\nYour absurd edits on gre...      1   
159546  "\n\nHey listen don't you ever!!!! Delete my e...      1   
159554  and i'm going to keep posting the stuff u dele...      1   

        severe_toxic  obscene  threat  insult  identity_hate  
6                  1        1       0       1              0  
12                 0        0       0       0              0  
16                 0        0       0       0              0  
42                 0        1       0       1              1  
43                 0        1       0       1              0  
...              ...      ...     ...     ...            ...  
159494             0        1       0       1              1  
159514             0        0       0       1              0  
159541             0        1       0       1              0  
159546             0        0       0       1              0  
159554             0        1       0       1              0  

[15294 rows x 7 columns]

In [5]:
df.head(7)

comment_text  toxic  severe_toxic  \
0  Explanation\nWhy the edits made under my usern...      0             0   
1  D'aww! He matches this background colour I'm s...      0             0   
2  Hey man, I'm really not trying to edit war. It...      0             0   
3  "\nMore\nI can't make any real suggestions on ...      0             0   
4  You, sir, are my hero. Any chance you remember...      0             0   
5  "\n\nCongratulations from me as well, use the ...      0             0   
6       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1             1   

   obscene  threat  insult  identity_hate  
0        0       0       0              0  
1        0       0       0              0  
2        0       0       0              0  
3        0       0       0              0  
4        0       0       0              0  
5        0       0       0              0  
6        1       0       1              0

In [6]:
df.iloc[6]['comment_text']

'COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK'

In [7]:
df.tail()

comment_text  toxic  \
159566  ":::::And for the second time of asking, when ...      0   
159567  You should be ashamed of yourself \n\nThat is ...      0   
159568  Spitzer \n\nUmm, theres no actual article for ...      0   
159569  And it looks like it was actually you who put ...      0   
159570  "\nAnd ... I really don't think you understand...      0   

        severe_toxic  obscene  threat  insult  identity_hate  
159566             0        0       0       0              0  
159567             0        0       0       0              0  
159568             0        0       0       0              0  
159569             0        0       0       0              0  
159570             0        0       0       0              0

In [8]:
pd.unique(df['comment_text'])
#reutrns a list of unique objects 

array(["Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       'Spitzer \n\nUmm, theres no actual article for prostitution ring.  - Crunch Captain.',
       'And it looks like it was actually you who put on the speedy to have the first version deleted now that I look at it.',
       '"\nAnd ... I really don\'t think you understand.  I came here and my idea was bad right away.  What kind of communit

In [9]:
 len(pd.unique(df['comment_text']))
# len(df['comment_text']) aese karke bhi dekh skta tha  
 

159571

In [10]:
#https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer
#the diff b/w tokenizer and 
#ye text vectorization se haar word ko specific id milegi like i ko 42 mila 
#fir him ko 2 mila aese words ki ek indexed dictionary banegi 
#so now time to slit data into data and labels 
x=df['comment_text']
x

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [11]:
df.columns[1:]
# ye aese : lga ne ka mtlb 2 se leke end tak 


Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [12]:
df[df.columns[1:]]
#now this will give output in data frame form 
#now we need to convert it into numpy array 

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [13]:
#df[df.columns[1:]] ye ek data frame hai  
y=df[df.columns[1:]].values
y
# and is ko numpy array me convert karne ke liye we use the function values


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [14]:
x[0].replace('\n',' ')

"Explanation Why the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [15]:
x= x.apply(lambda t : t.replace('\n',' '))
x
#https://stackoverflow.com/questions/23669024/how-to-strip-a-specific-word-from-a-string 
# for replacing a word in the string 
#https://sparkbyexamples.com/pandas/pandas-apply-with-lambda-examples/ for applying lambda function on python 


0         Explanation Why the edits made under my userna...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         " More I can't make any real suggestions on im...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself   That is a ...
159568    Spitzer   Umm, theres no actual article for pr...
159569    And it looks like it was actually you who put ...
159570    " And ... I really don't think you understand....
Name: comment_text, Length: 159571, dtype: object

In [16]:
max_features=200000#number of words in vocab

In [17]:
vectorizer=tf.keras.layers.TextVectorization(
max_tokens=max_features,
output_sequence_length=1800,# means ki snetence max 1800 words ka ho skta hai 
output_mode='int'# means ki haar ek word ko ek int value denge not the one hot encodign type 
)

2023-02-11 10:31:55.943848: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-11 10:31:56.029788: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-11 10:31:56.030665: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-11 10:31:56.033237: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

In [18]:
type(x)

pandas.core.series.Series

In [19]:
#now to convert x to numpy array x.values karlena series data ko numpy array me change karne ke liye 
type(x.values)
x.values
x

0         Explanation Why the edits made under my userna...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         " More I can't make any real suggestions on im...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself   That is a ...
159568    Spitzer   Umm, theres no actual article for pr...
159569    And it looks like it was actually you who put ...
159570    " And ... I really don't think you understand....
Name: comment_text, Length: 159571, dtype: object

In [20]:
x.values

array(["Explanation Why the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       'Spitzer   Umm, theres no actual article for prostitution ring.  - Crunch Captain.',
       'And it looks like it was actually you who put on the speedy to have the first version deleted now that I look at it.',
       '" And ... I really don\'t think you understand.  I came here and my idea was bad right away.  What kind of community go

In [21]:
type(x.values)

numpy.ndarray

In [22]:
#abi  i will call adapt 
#During adapt(), the layer will build a vocabulary of all string tokens seen in the dataset,
# sorted by occurrence count, with ties broken by sort order of the tokens (high to low). 
#At the end of adapt(), if max_tokens is set, the vocabulary wil be truncated to max_tokens size.
vectorizer.adapt(x.values)

2023-02-11 10:31:58.795273: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


In [23]:
vectorizer.get_vocabulary()



['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [24]:
vectorizer('hellow hello dirty fellow')
# so thie was as we pass a word to vectorizer it converts 

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([88393,   288,  2298, ...,     0,     0,     0])>

In [25]:
#if i wanna se the 1st 4 values 
vectorizer('hellow hello dirty fellow')[:4]


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([88393,   288,  2298,  1741])>

In [26]:
# now we need to make a vectorized data set 
vectorized_text = vectorizer(x)
vectorized_text
#159571 ,1800 ki shape isliye hai coz  159571 to  lenght of x hai and 1800 coz we set the max limit to 1800 words


2023-02-11 10:32:17.830869: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2297822400 exceeds 10% of free system memory.


<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]])>

In [27]:
#bhale hi ma x.values karke paas karu ya x karke pass karu output is eager tensor 
type(vectorized_text)

tensorflow.python.framework.ops.EagerTensor

In [28]:
# The tf.data.Dataset class .prefetch() function is used to produce a dataset that prefetches the specified elements from this given dataset.

# Syntax:
# https://www.tensorflow.org/guide/data_performance for cache 
dataset=tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset=dataset.cache()# it will convert the dataset into cache and store it in memory  instead of ram
dataset=dataset.shuffle(160000) # ye ju bracket ke andar hai ye buffer size hai 
#https://colab.research.google.com/drive/1VS6-dYk3YAzoRmALhgTK7bb2_tBPrB4c?usp=sharing to understand the function of 
# .shuffle and .repeat 
# and how does a batch is formed 
#https://stackoverflow.com/questions/53514495/what-does-batch-repeat-and-shuffle-do-with-tensorflow-datasetb
# dataset=dataset.repeat() #ye repeat wali cheez ka matlab ni sammajh aaya 
# agar ma buffer data chota kardu to it shows a warning 
dataset=dataset.batch(16)
dataset=dataset.prefetch(16)

In [29]:
# now we can see using numpy iterator our batches 
dataset.as_numpy_iterator()

2023-02-11 10:32:19.467024: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2297822400 exceeds 10% of free system memory.


In [30]:
dataset.as_numpy_iterator().next()
# ye next function use karne se everytime i refresh it will show the next data set

2023-02-11 10:32:21.283900: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2297822400 exceeds 10% of free system memory.


(array([[   49,     7,    51, ...,     0,     0,     0],
        [ 4548,  6810,  2004, ...,     0,     0,     0],
        [ 3436,    38,  1568, ...,     0,     0,     0],
        ...,
        [  462, 46049,   485, ...,     0,     0,     0],
        [  850,   562,   179, ...,     0,     0,     0],
        [95517,     4,     2, ...,     0,     0,     0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [31]:
batch_x ,batch_y=dataset.as_numpy_iterator().next()

2023-02-11 10:32:23.718438: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2297822400 exceeds 10% of free system memory.


In [32]:
 batch_x

array([[  696,     2,    24, ...,     0,     0,     0],
       [90752,   189,  3192, ...,     0,     0,     0],
       [    8,   244,    10, ...,     0,     0,     0],
       ...,
       [ 1456,    81,     1, ...,     0,     0,     0],
       [    8,   130,   201, ...,     0,     0,     0],
       [ 1312,   454,  2341, ...,     0,     0,     0]])

In [33]:
batch_y
#this way we can decompse the batch in data and labels 


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [34]:
# wo repeat function lga ne ki wajah se ye dataset ke lenght infinte bta rha the so dunn use repeat until 
# you know its proper function 


In [35]:
# time ro break data in traning testing and validation 
train = dataset.take(int(len(dataset)*.7))
# so what is happening is data set me data is in form of batches so un batches ki lenght li phle 
# fir us ko 0.7 se multiply kia and fir us ko int me convert kia and int me convert hone ke baad
# jo number aaya utta partition le lia using the take method

In [36]:
val=dataset.skip(int(len(dataset)*0.7)).take(int(len(dataset)*0.2))
# is me upar ka 0.7 jo use kia tha training data ke liye wo to skip kar dia 
# and jo niiche ka 30 percent tha us me se 20% validation ke liye le liya 

In [37]:
test=dataset.skip(int(len(dataset)*0.9)).take(int(len(dataset)*0.1))
#just like thee validation data set

In [38]:
len(train)

6981

In [39]:
train.as_numpy_iterator().next()

2023-02-11 10:32:25.855102: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2297822400 exceeds 10% of free system memory.


(array([[1540,  179, 1942, ...,    0,    0,    0],
        [ 148,   90,    8, ...,    0,    0,    0],
        [  20,   37, 3205, ...,    0,    0,    0],
        ...,
        [   2,  413,  310, ...,    0,    0,    0],
        [   8,  710,   22, ...,    0,    0,    0],
        [  49,   40,  485, ...,    0,    0,    0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [40]:
#https://stats.stackexchange.com/questions/270546/how-does-keras-embedding-layer-work this is how 
#an embedding layer works 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import LSTM, Dropout,Bidirectional,Dense,Embedding,BatchNormalization

In [41]:
#the LSTM commonly uses the Sigmoid activation for recurrent connections and the Tanh activation for output.
initializer = tf.keras.initializers.HeNormal()
model=Sequential()
model.add(Embedding(max_features,32))
model.add(Bidirectional(LSTM(32,activation='tanh')))
model.add(BatchNormalization())
# model.add(Bidirectional(LSTM(64,activation='tanh')))
# model.add(BatchNormalization())
# for some reason adding 2 bidirecitional lstm layer doesnt seem to work it shows an error 
model.add(Dense(128,activation='relu',kernel_initializer=initializer ))
model.add(BatchNormalization())
model.add(Dense(256,activation='relu',kernel_initializer=initializer))
model.add(BatchNormalization())
model.add(Dense(128,activation='relu',kernel_initializer=initializer))
model.add(BatchNormalization())
model.add(Dense(6,activation='sigmoid',kernel_initializer=initializer))
# ye 6 isliye coz w 6 colums hai toxic and all wale and sigmoid isliye coz 
# sub ka output 0-1 ke beech hai
#more on embedding layer https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding
# ye regularizer ke andar l2(1)  jese 1 likha hai to is ka mtlb haai ki se zyda ni hogi weights ki value



In [42]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 32)          6400000   
_________________________________________________________________
bidirectional (Bidirectional (None, 64)                16640     
_________________________________________________________________
batch_normalization (BatchNo (None, 64)                256       
_________________________________________________________________
dense (Dense)                (None, 128)               8320      
_________________________________________________________________
batch_normalization_1 (Batch (None, 128)               512       
_________________________________________________________________
dense_1 (Dense)              (None, 256)               33024     
_________________________________________________________________
batch_normalization_2 (Batch (None, 256)               1

In [43]:
initial_learning_rate = 0.1
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate,
    decay_steps=10000,
    decay_rate=0.96,
    staircase=True)

model.compile(
  optimizer=tf.keras.optimizers.Adadelta(learning_rate=lr_schedule),
  loss=tf.keras.losses.BinaryCrossentropy(),
  metrics=['accuracy'])
# ye staircase= true rakh ne se floow function type kuch apply ho jata hai which converts it into 
#integer  wo ek cosine function use karlia tha a ne wo image cassification project me 
# to fir us me us staircase wali cheez ni thi to model error throw kaar rha tha mera
# wo kernel regularizer lga te hai loss exploded .-. ya to us ki value i sset to 0.01 to it be goo 
# wrna 1 rakh ne pe to it exploded 

In [ ]:
# https://www.geeksforgeeks.org/enumerate-in-python/ ye emurate function is used to print 
# which element was  from the data at which iteration when its int loop 
hist=model.fit(train, 
    epochs=5, 
    validation_data=val
#    callbacks=[early_stopping]
)
# in this case we dont need early stopping since we will train for about 10 epochs max

Epoch 1/5


2023-02-11 10:32:38.760759: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8005


6981/6981 [==============================] - 794s 113ms/step - loss: 0.1829 - accuracy: 0.6983 - val_loss: 0.1108 - val_accuracy: 0.9196
Epoch 2/5
6981/6981 [==============================] - 788s 113ms/step - loss: 0.0944 - accuracy: 0.9442 - val_loss: 0.0916 - val_accuracy: 0.9689
Epoch 3/5
6981/6981 [==============================] - 788s 113ms/step - loss: 0.0826 - accuracy: 0.9559 - val_loss: 0.0977 - val_accuracy: 0.9067
Epoch 4/5
6981/6981 [==============================] - ETA: 0s - loss: 0.0755 - accuracy: 0.9582

test


In [ ]:
hist

In [ ]:
# test=pd.read_csv('/kaggle/input/jigsaw-toxic-comment-classification-challenge/test.csv')
# test.drop(['id'],axis=1,inplace=True)
# test['comment_text'] =test['comment_text'].apply(lambda t : t.replace('\n',' '))

# test=test.values
# test
# test_labels=pd.read_csv('/kaggle/input/jigsaw-toxic-comment-classification-challenge/test_labels.csv')
# test_labels.drop(['id'],axis=1,inplace=True)
# test_labels['toxic']=test_labels['toxic'].map({-1:1})
# test_labels['severe_toxic']=test_labels['severe_toxic'].map({-1:1})
# test_labels['obscene']=test_labels['obscene'].map({-1:1})
# test_labels['threat']=test_labels['threat'].map({-1:1})
# test_labels['insult']=test_labels['insult'].map({-1:1})
# test_labels['identity_hate']=test_labels['identity_hate'].map({-1:1})
# test_labels['toxic']=test_labels['toxic'].fillna(0)
# test_labels['severe_toxic']=test_labels['severe_toxic'].fillna(0)
# test_labels['obscene']=test_labels['obscene'].fillna(0)
# test_labels['threat']=test_labels['threat'].fillna(0)
# test_labels['insult']=test_labels['insult'].fillna(0)
# test_labels['identity_hate']=test_labels['identity_hate'].fillna(0)
# test=vectorizer(test)
# test_labels.values
# test_dataset=tf.data.Dataset.from_tensor_slices((test,test_labels))
# test_dataset=test_dataset.cache()
# test_dataset=test_dataset.shuffle(160000)


# test_dataset=test_dataset.batch(16)
# test_dataset=test_dataset.prefetch(16)






In [ ]:
hist.history

In [ ]:
import matplotlib.pyplot as plt 
fig=plt.figure()
plt.plot(hist.history['loss'],color='teal',label='loss')
plt.plot(hist.history['val_loss'],color='blue',label='val_loss')
fig.suptitle('loss',fontsize=28)
plt.legend(loc='upper left')
plt.show()

In [ ]:
from tensorflow.keras.metrics import Precision,Recall,CategoricalAccuracy
# the reason i sued categorical accuracy instead of accuracy is coz 
#  Accuracy is just comparison b/w target values match the predicted values
# categorical accuracy on the other hand calculates the percentage of predicted values 
# that match with actual values 

In [ ]:
pre=Precision()
rec=Recall()
cat_acc=CategoricalAccuracy()

In [ ]:
batch_y

In [ ]:
batch_y.flatten()

In [ ]:
for batch in test.as_numpy_iterator():
    x_test,y_true=batch
    yhat=model.predict(x_test)
   
    
    pre.update_state(y_true,yhat)
    rec.update_state(y_true,yhat)
    cat_acc.update_state(y_true,yhat)
# ye update state acts updates the values for eveery y_hat,y true

In [ ]:
print( 'the precision is',pre.result().numpy())

In [ ]:
print('the recall is',rec.result().numpy())

In [ ]:
print('the accuracy is',cat_acc.result().numpy())

In [ ]:
# in this case dont flatten it wont work due to the working of how categorical accuracy works 
model.save('toxicity.h5')

In [ ]:
# if we want to reload the model we can use tf.keras.models.load_model('toxicity.h5')
res=vectorizer(' you are an idiot ')
t= model.predict(np.expand_dims(res,0))

In [ ]:
t>0.49

In [ ]:
df.columns[1:]

In [ ]:
df[df['threat']==1]


In [ ]:
# for batch in test_dataset.as_numpy_iterator():
#     x_test,y_true=batch
#     yhat=model.predict(x_test)
   
    
#     pre.update_state(y_true,yhat)
#     rec.update_state(y_true,yhat)
#     cat_acc.update_state(y_true,yhat)

In [ ]:
# test_dataset


In [ ]:
# dataset